### ISSUE TITLE
Pushing attachments with incoming mails.

### ISSUE THREAD

**Issue by r0hi7** [TrashEmail/TrashEmail#12]
**Is your feature request related to a problem? Please describe.**
In the current release if the user gets an email with attachments, then the attachments gets ignored.

**Describe the solution you'd like**
In case incoming mail contains an attachment, it should be forwarded to the telegram client as well.

**Describe alternatives you've considered**
Can we have attachment scanning with VT APIs?

**Comment by nishitm** [comment]
closing this issue, as this feature is added into the service. 
thanks
