### ISSUE TITLE
HTML version of email link not over HTTPS

### ISSUE THREAD

**Issue by dcRUSTy** [TrashEmail/TrashEmail#58]
**Describe the bug**
There is button to display "HTML Version" of email. It redirects with an http:// URL and not https://

**To Reproduce**
1. Send urself an email (with HTML content?)
2. In bot click on "HTML Verison" button

**Expected behavior**
URL must begin with https://

**Screenshots**
![notHTTPS](https://user-images.githubusercontent.com/40319304/87240284-e1461a00-c435-11ea-9742-230d7914b114.jpg)

**Comment by r0hi7** [comment]
@dcRUSTy I agree to this, but the `http` to `https` redirection is done at webserver layer. So even if you are see this html link, there is redirect call happening at the server layer which will move to https. You can check that out in your browser.

I will keep this issue open till then 😄

**Comment by dcRUSTy** [comment]
![wireshark](https://user-images.githubusercontent.com/40319304/87241523-a6e27a00-c441-11ea-9c68-ad2204f58ff1.JPG)
The redirection is way too late.... the email URL/UUID.html is in plaintext visible to anyone(sniffer) on the network.

**Comment by r0hi7** [comment]
@dcRUSTy it is not the case. The domain and uri are anyway submitted in plaintext even with https. The only role of https is to prevent data not the host uri.
You can refer to this question https://stackoverflow.com/questions/8277323/what-information-is-visible-to-a-packet-sniffer-which-intercepted-a-https-packet

**Comment by dcRUSTy** [comment]
For example url is **https**://_example.com_/**1-2-3-4.html** then sniffer can only get to know **example.com**
if url is on **http**://_example.com_/**1-2-3-4.html**  then sniffer can see **example.com** along with **1-2-3-4.html**. Trust me

**Comment by r0hi7** [comment]
Oh yes! That is the case I think, I missed in the first shot. I think it will be a quick fix. Will fix this up. Thanks for pointing this out.

**Comment by r0hi7** [comment]
Thanks @dcRUSTy. This has been fixed and rolled to production as well. It was just a config change, so no code change is there to point to any commit. Check that out, I am closing this for now.
