### ISSUE TITLE
TrashEmail Stats endpoint not working.

### ISSUE THREAD

**Issue by r0hi7** [TrashEmail/TrashEmail#65]

**Comment by Suleman-Elahi** [comment]
Would it be possible for you to host a status page for the bot? Right now I can't delete email addresses that I created earlier in June and can't receive emails on them either.

**Comment by r0hi7** [comment]
This might have happened during the clean up process. I can help you out manually in this case. Will it be possible for you to share with me the list of emails that you want to remove.
Also can you please elaborate what do you mean by Status page for the bot ?

**Comment by Suleman-Elahi** [comment]
A status page displays the information about API endpoints or basically any HTTP route by constantly monitoring it. You can display error messages or show the uptime graph or even place a maintenance status for people to let them know if the service is up or down. Freshstatus(https://www.freshworks.com/status-page/) lets you create a free status page and you may give it a try if you want to.

Email I want to delete: slmnxx@trashemail.in

**Comment by r0hi7** [comment]
Sorry for the delay in response @Suleman-Elahi . I have deleted that email id for you. You can check that in list now. Also, thanks for sharing the freshworks.com. I will definitely look into this :)

**Comment by r0hi7** [comment]
The new status endpoint of every single information that is crucial for public view is now hosted @ https://trashemail.in
